"""
Per-script run-variant declarations.

When a single script needs to run with several different parameter sets (e.g. once
per travel mode, or once per year), `Variants` lets you declare the valid variants
alongside the code that uses them. The boilerplate for selecting one from the
command line and dispatching to `main(...)` is folded into `Variants.run()`.

Typical pattern at the bottom of a script:

    variants = Variants([('mode', str)])
    variants.add(name='walk', mode='walk')
    variants.add(name='bike', mode='bike')

    def main(variant):
        context = init_context(variant)
        ...
        context.close()

    if __name__ == '__main__':
        variants.run(main)

Default invocation runs all variants sequentially:
    python script.py
A single variant by name:
    python script.py --variant bike
External orchestration (bash fan-out, DVC `foreach`, Snakemake wildcards) calls
the script once per variant and parallelizes upstream.
"""

from dataclasses import dataclass
from typing import Callable

from aperta_atlas.utils import tracked_namedtuple


@dataclass(frozen=True)
class _Entry:
    """Internal: one declared variant. `tuple` is the tracked-namedtuple instance."""
    name: str
    tuple: object


class Variants:
    labels: list[str]
    variant_tuple_factory: type
    _entries: list[_Entry]

    def __init__(self, labels_and_types: list[tuple[str, type]]) -> None:
        self.labels = [label_and_type[0] for label_and_type in labels_and_types]
        # The variant tuple carries a leading `name` field alongside the
        # user-declared axes so `main(variant)` can read `variant.name`
        # directly (e.g. for output filenames) without a lookup.
        self.variant_tuple_factory = tracked_namedtuple(
            [('name', str), *labels_and_types])
        self._entries = []

    def add(self, name: str | None = None, **kwargs) -> None:
        """Add a variant.

        Args:
            name: human-friendly identifier used by `get()`, `--variant`,
                and made available on the tuple as `variant.name`. If
                omitted, a name is auto-generated by joining parameter
                values with '_' (matching `Context.variant_suffix`).
            kwargs: parameter values, must cover exactly `self.labels`.
        """
        if set(self.labels) != set(kwargs.keys()):
            raise ValueError(f"Supplied variant parameters {sorted(kwargs)} do not match "
                             f"required parameters {sorted(self.labels)}.")
        if name is None:
            name = '_'.join(str(kwargs[label]) for label in self.labels)
        if any(e.name == name for e in self._entries):
            raise ValueError(f"Duplicate variant name: '{name}'.")
        v = self.variant_tuple_factory(name=name, **kwargs)
        self._entries.append(_Entry(name=name, tuple=v))

    @property
    def names(self) -> list[str]:
        """Public read-only list of declared variant names, in declaration order."""
        return [e.name for e in self._entries]

    def get(self, which: str | int) -> list[object]:
        """Look up variants.

        Accepted forms for `which`:
            - 'all'        : every declared variant
            - 'first'      : first variant
            - <name>       : the single variant with that name (matches `add(name=...)`)
            - <int>        : single variant by index
        """
        if isinstance(which, str):
            if which == 'first':
                return [self._entries[0].tuple] if self._entries else []
            if which == 'all':
                return [e.tuple for e in self._entries]
            for e in self._entries:
                if e.name == which:
                    return [e.tuple]
            raise ValueError(f"Unknown variant selector '{which}'. Known names: {self.names}.")
        if isinstance(which, int):
            return [self._entries[which].tuple]
        raise ValueError(f"`which` must be str or int (got {type(which)}).")

    def run(self, main_fn: Callable, default: str = 'all') -> None:
        """Parse the `--variant` CLI argument and dispatch to `main_fn` for each selected variant.

        Also accepts (and silently passes through) `--scenario <name>`: that flag is
        read by `aperta.context.init_context` from sys.argv, so any script doing
        `init_context(variant)` from a project namespace will pick it up automatically.
        For preparation namespaces, passing `--scenario` is rejected by `init_context`.

        `default` is the value used when `--variant` is not provided.
        """
        import argparse
        p = argparse.ArgumentParser()
        p.add_argument('--variant', default=default,
                       help=f"'all', 'first', a variant name, or an integer index "
                            f"(default: {default!r}). Known names: {self.names or '(none)'}.")
        p.add_argument('--scenario', default=None,
                       help="Scenario name (required for projects/ namespaces; forbidden "
                            "for preparation/). Read by init_context(); no need to thread "
                            "through main().")
        args = p.parse_args()
        for v in self.get(args.variant):
            main_fn(v)
